const VERIFICATION_CODE_EXPIRY = 10 * 60 * 1000; // 10 minutos
const PASSWORD_MIN_LENGTH = 8;
const USERNAME_MIN_LENGTH = 3;
const USERNAME_MAX_LENGTH = 50;

module.exports = {
  VERIFICATION_CODE_EXPIRY,
  PASSWORD_MIN_LENGTH,
  USERNAME_MIN_LENGTH,
  USERNAME_MAX_LENGTH,
};
